### ISSUE TITLE
acc and el vs. prev and current

### ISSUE THREAD

**Issue by shiryz** [ZooeyMiller/mc-array-methods-reduce#3]
I find it a lot easier to understand the code of reduce when the function is written with `((prev, current) =>...)` instead of accumulator and element (el).

**Comment by ZooeyMiller** [comment]
I find that the `(prev, current)` naming of arguments can be confusing, since the accumulator is not the previous element, it can be something different entirely.

I've not seen the `(prev, current)` pattern before, but feel it is probably more misleading in how reduce works than clarifying. 

If, given this, you're comfortable with the solutions staying as is, then feel free to close the issue. If not, let's try to find a different naming convention we are both comfortable with.

**Comment by shiryz** [comment]
@ZooeyMiller looking at the [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce) in MDN they use `(acc, current)`, TBH I don't mind any naming convention but would prefer the one they use if it's clearer for the students.
I'll close if you prefer acc and el :smiley_cat:.

**Comment by ZooeyMiller** [comment]
@shiryz I'm comfortable with acc + current. will modify solution to this.
